# Generated by Django 4.2.4 on 2023-08-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("biography", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("Categeoryname", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=1000)),
                ("ISBN", models.CharField(max_length=13, unique=True)),
                ("summary", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("publish_date", models.DateField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                ("stock", models.PositiveBigIntegerField()),
                ("author", models.ManyToManyField(to="books.author")),
                ("category", models.ManyToManyField(to="books.category")),
            ],
        ),
    ]
